import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <nav className='bg-gray-800 '>
      <div className="relative flex h-16 items-center justify-between ">Recipe App</div></nav>
      {children}
      </body>
    </html>
  );
}
